### ISSUE TITLE
java.util.NoSuchElementException: No value present

### ISSUE THREAD

**Issue by pisaiah** [GlowstonePlusPlus/Bukkit2Sponge#14]
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Unknown Source) ~[?:1.8.0_131]
        at net.glowstone.bukkit2sponge.Bukkit2Sponge.load(Bukkit2Sponge.java:102) ~[?:?]
        at net.glowstone.bukkit2sponge.Bukkit2Sponge.onEnable(Bukkit2Sponge.java:46) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[Bukkit.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [Bukkit.jar:?]

Running Minecraft 1.12.
Running latest jar downloaded from the link in README.md:
https://bamboo.gserv.me/browse/GSPP-B2S/latestSuccessful/artifact/shared/Plugin-JAR/bukkit2sponge-0.1.0-SNAPSHOT.jar

**Comment by satoshinm** [comment]
@IsaiahPatton what Bukkit server platform and version? I am not seeing this on Glowstone server build 551 or Spigot d5dfb24-ed8c725 (MC: 1.12).

Crash is [here](https://github.com/GlowstoneMC/Bukkit2Sponge/blob/master/src/main/java/net/glowstone/bukkit2sponge/Bukkit2Sponge.java#L102), in getting the platform version:

```java
            getLogger().info("SpongeAPI version: " + game.getPlatform().getContainer(Platform.Component.API).getVersion().get());
```
