### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by deathcap** [GlowstonePlusPlus/Bukkit2Sponge#7]
Register commands from SpongeAPI plugins with the Bukkit API

Complication: in Bukkit, commands are normally statically defined in the plugin.yml file. The command handler instance in the plugin manager is private: http://bukkit.org/threads/dynamic-commands.132138/

**Comment by deathcap** [comment]
Commands are now registered, testing with https://github.com/boformer/SimpleMail:

```
>help
00:34:53 [INFO] /mail: Send and receive mails

>help mail
00:35:34 [INFO] --------- Help: /mail ---------------------------
00:35:34 [INFO] Description: Send and receive mails
00:35:34 [INFO] Usage: 
00:35:34 [INFO] Aliases: SimpleMail:mail
```

but more work is needed to get commands to execute, currently fails with:

```
>mail
00:34:57 [SEVERE] Error while executing GlowTask{id=1, plugin=null, sync=true: net.glowstone.ConsoleManager$CommandTask@1d858d01}
org.bukkit.command.CommandException: Unhandled exception executing 'mail' in io.github.deathcap.bukkit2sponge.command.BukkitCommand(mail)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:185)
    at net.glowstone.GlowServer.dispatchCommand(GlowServer.java:1120)
    at net.glowstone.ConsoleManager$CommandTask.run(ConsoleManager.java:205)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at net.glowstone.scheduler.GlowTask.run(GlowTask.java:163)
    at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:181)
    at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:24)
    at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:110)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at org.spongepowered.api.text.Texts.toPlain(Texts.java:401)
    at org.spongepowered.api.util.TextMessageException.getMessage(TextMessageException.java:83)
    at org.spongepowered.api.util.TextMessageException.getLocalizedMessage(TextMessageException.java:98)
    at java.lang.Throwable.toString(Throwable.java:480)
    at java.lang.String.valueOf(String.java:2847)
    at java.io.PrintStream.println(PrintStream.java:821)
    at java.lang.Throwable$WrappedPrintStream.println(Throwable.java:748)
    at java.lang.Throwable.printStackTrace(Throwable.java:655)
    at java.lang.Throwable.printStackTrace(Throwable.java:643)
    at java.lang.Throwable.printStackTrace(Throwable.java:634)
    at io.github.deathcap.bukkit2sponge.command.BukkitCommand.execute(BukkitCommand.java:66)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
    ... 15 more
```

same error as in https://github.com/SpongePowered/SpongeAPI/commit/38acf16861b99c76c8df23f8fceabe896217318b#commitcomment-10900228

> You need to set it at runtime, either using reflection or using some kind of access transformer.

**Comment by deathcap** [comment]
After #8 TextFactory implementation and https://github.com/deathcap/Bukkit2Sponge/commit/d719055c995c2d6c82846612342cabdc692a6901 some rudimentary permissions implementation, now can execute the simplest SimpleMail commands:

```
>mail read
01:09:21 [INFO] ShinyConsoleSource sendMessage: --- Your Inbox ---
01:09:21 [INFO] ShinyConsoleSource sendMessage: No mails in your inbox.
>mail clear
01:09:23 [INFO] ShinyConsoleSource sendMessage: Inbox cleared!
```
